name: actuator-tester
author: vu-ase
source: github.com/VU-ASE/actuator-tester
version: 1.0.0
description: Service to assist users with calibration and testing of motors over a UDP connection
as: controller

commands:
  build: make build
  run: ./bin/actuator-tester

inputs: []

outputs:
  - decision

configuration:
  - name: udp-port
    tunable: true
    type: string
    value: ":8080"

  - name: udp-tuning # if set to 1 then will ignore webui changes and wait for udp messages
    tunable: true
    type: number
    value: 0

  - name: channel
    tunable: true
    type: number
    value: 0

  - name: value
    tunable: true
    type: number
    value: 0


